log:
  level: "info"

server:
  port: "8080"
  shutdown_timeout: "10s"
  max_upload_size: "1MB"

database:
  driver: "sqlite"
  sqlite:
    path: "data/database.db"
    seed: true
  mysql:
    host: "localhost"
    port: "3306"
    database: "phonon"
    username: "phonon"
    password: "phonon_password"

storage:
  type: "local"
  local:
    base_path: "./data/user/audio"

mq:
  kafka:
    brokers:
      - "localhost:9092"
    audio_conversion:
      group: "main"
      topic: "audio_conversion"
