log:
  level: "info"

server:
  port: "8080"
  shutdown_timeout: "10s"

database:
  driver: "sqlite"
  sqlite:
    path: "data/database.db"
    seed: true

storage:
  type: "local"
  local:
    base_path: "./data"

mq:
  kafka:
    brokers:
      - "localhost:9092"
    group: "test"
    topic: test
